version: 2
sphinx:
  configuration: docs/source/conf.py
build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - python3.10 setup.py install
      - sphinx-apidoc -f -o docs/source/api zython
